
import type { Product, Vendor } from './types';

export const VENDORS: Vendor[] = [
  {
    id: 'v1',
    name: 'Artisan Crafts Co.',
    logoUrl: `https://picsum.photos/seed/v1logo/100/100`,
    rating: 4.8,
    description: 'Handmade crafts with a touch of modern elegance. Each piece tells a story.',
    coverImageUrl: `https://picsum.photos/seed/v1cover/1200/400`,
  },
  {
    id: 'v2',
    name: 'Future Tech Gadgets',
    logoUrl: `https://picsum.photos/seed/v2logo/100/100`,
    rating: 4.9,
    description: 'Cutting-edge gadgets and accessories to simplify and enhance your life.',
    coverImageUrl: `https://picsum.photos/seed/v2cover/1200/400`,
  },
  {
    id: 'v3',
    name: 'Vintage Threads',
    logoUrl: `https://picsum.photos/seed/v3logo/100/100`,
    rating: 4.6,
    description: 'Curated collection of timeless vintage clothing and accessories.',
    coverImageUrl: `https://picsum.photos/seed/v3cover/1200/400`,
  },
    {
    id: 'v4',
    name: 'Green Thumb Botanics',
    logoUrl: `https://picsum.photos/seed/v4logo/100/100`,
    rating: 4.9,
    description: 'Organic and sustainably grown plants to bring nature into your home.',
    coverImageUrl: `https://picsum.photos/seed/v4cover/1200/400`,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Hand-Carved Wooden Bowl',
    description: 'A beautiful and unique bowl, hand-carved from sustainable mango wood. Perfect for salads, fruits, or as a decorative centerpiece.',
    price: 45.00,
    imageUrl: `https://picsum.photos/seed/p1/500/500`,
    gallery: [`https://picsum.photos/seed/p1g1/800/600`, `https://picsum.photos/seed/p1g2/800/600`, `https://picsum.photos/seed/p1g3/800/600`],
    vendorId: 'v1',
    rating: 4.7,
    category: 'Home Goods',
    reviewCount: 124,
  },
  {
    id: 'p2',
    name: 'Smart Ambient Desk Lamp',
    description: 'A sleek, minimalist desk lamp that syncs with your devices. Features customizable colors, brightness levels, and smart assistant integration.',
    price: 89.99,
    imageUrl: `https://picsum.photos/seed/p2/500/500`,
    gallery: [`https://picsum.photos/seed/p2g1/800/600`, `https://picsum.photos/seed/p2g2/800/600`],
    vendorId: 'v2',
    rating: 4.9,
    category: 'Electronics',
    reviewCount: 218,
  },
  {
    id: 'p3',
    name: 'Classic 1980s Denim Jacket',
    description: 'An authentic vintage denim jacket from the 80s. Perfectly worn-in with a timeless style that never fades.',
    price: 120.00,
    imageUrl: `https://picsum.photos/seed/p3/500/500`,
    gallery: [`https://picsum.photos/seed/p3g1/800/600`, `https://picsum.photos/seed/p3g2/800/600`, `https://picsum.photos/seed/p3g3/800/600`],
    vendorId: 'v3',
    rating: 4.8,
    category: 'Apparel',
    reviewCount: 45,
  },
  {
    id: 'p4',
    name: 'Ceramic Self-Watering Planter',
    description: 'A stylish ceramic planter with a built-in self-watering system, ensuring your plants get the perfect amount of moisture.',
    price: 35.50,
    imageUrl: `https://picsum.photos/seed/p4/500/500`,
    gallery: [`https://picsum.photos/seed/p4g1/800/600`],
    vendorId: 'v1',
    rating: 4.9,
    category: 'Home Goods',
    reviewCount: 98,
  },
  {
    id: 'p5',
    name: 'Portable Power Bank (20000mAh)',
    description: 'Ultra-high capacity power bank that can charge your smartphone up to 5 times. Features fast-charging and multiple output ports.',
    price: 49.99,
    imageUrl: `https://picsum.photos/seed/p5/500/500`,
    gallery: [`https://picsum.photos/seed/p5g1/800/600`, `https://picsum.photos/seed/p5g2/800/600`],
    vendorId: 'v2',
    rating: 4.7,
    category: 'Electronics',
    reviewCount: 512,
  },
  {
    id: 'p6',
    name: 'Silk Scarf - Floral Print',
    description: 'A luxurious 100% silk scarf with a vibrant, vintage-inspired floral print. A versatile accessory for any season.',
    price: 65.00,
    imageUrl: `https://picsum.photos/seed/p6/500/500`,
    gallery: [`https://picsum.photos/seed/p6g1/800/600`, `https://picsum.photos/seed/p6g2/800/600`],
    vendorId: 'v3',
    rating: 4.9,
    category: 'Accessories',
    reviewCount: 78,
  },
  {
    id: 'p7',
    name: 'Monstera Deliciosa Plant',
    description: 'A healthy, well-rooted Monstera Deliciosa. Known for its iconic split leaves, it\'s a stunning and easy-to-care-for houseplant.',
    price: 55.00,
    imageUrl: `https://picsum.photos/seed/p7/500/500`,
    gallery: [`https://picsum.photos/seed/p7g1/800/600`, `https://picsum.photos/seed/p7g2/800/600`],
    vendorId: 'v4',
    rating: 5.0,
    category: 'Plants',
    reviewCount: 150,
  },
  {
    id: 'p8',
    name: 'Snake Plant (Sansevieria)',
    description: 'A hardy and air-purifying Snake Plant. Its striking upright leaves make a bold statement in any room.',
    price: 30.00,
    imageUrl: `https://picsum.photos/seed/p8/500/500`,
    gallery: [`https://picsum.photos/seed/p8g1/800/600`],
    vendorId: 'v4',
    rating: 4.8,
    category: 'Plants',
    reviewCount: 112,
  },
];
